const gameQuestions = {
    ja: [
        "今の状況、攻める？ 守る？ それとも引く？",
        "次のターゲット、誰にする？",
        "手持ちのアイテム、ここで出し惜しみする？ それとも使う？",
        "今のピンチ、誰のせいにしちゃう？",
        "次の部屋に入る前に、しっかり回復しとく？",
        "今の戦闘、誰のファインプレーだった？",
        "この選択、慎重に行く？ それともノリと勢いで行く？",
        "やばい、これ全滅の危機ある？ それともいける？",
        "次の道、右と左どっちの直感が働く？",
        "今のうちにセーブしとく？ まだ先に進む？",
        "この敵、弱点ってどこだと思う？",
        "手に入った新しい装備、誰に持たせる？",
        "今の攻撃、ギリギリ避けた？ それとも直撃した？",
        "次の作戦、誰が囮役を引き受ける？",
        "そろそろ撤退の二文字が頭をよぎる？",
        "この怪しい罠、誰が解除に挑戦する？",
        "今のうちにバフや回復をかけ直す？",
        "ここから一気に形勢逆転できると思う？",
        "次のイベント、嫌な予感がしない？",
        "この選択肢、沼る（泥沼化する）予感がする？",
        "今のミス、誰をいじる？",
        "お互いの残りHP、安全圏？ それとも危険？",
        "そろそろ強力なスキルや必殺技をブッパする？",
        "次のエリアに行く前に、やり残した探索はない？",
        "この状況、何か良い打開策思いついた？",
        "今のコンボ、綺麗に決まって気持ちよくなかった？",
        "敵の数が多くない？ 気のせい？",
        "今一番頼りにしてる回復手段は何？",
        "ここ、一か八かで突っ込む？",
        "次のターン、何する予定？",
        "この選択、後ですごく後悔しそう？",
        "味方の巻き込みや誤射にヒヤッとした？",
        "そろそろボスのHP、半分切ったと思う？",
        "今のダメージ、痛かった？ 余裕？",
        "このピンチ、気合いで乗り切れそう？",
        "次の行動順、誰から動くのがベスト？",
        "手持ちの資金、そろそろ使い切っちゃう？",
        "この選択、全員一致ですぐ決まりそう？",
        "今のうちに、作戦を立て直す時間取る？",
        "ラスト一撃、誰にカッコよく決めてもらう？"
    ],
    en: [
        "For our current situation, should we attack, defend, or fall back?",
        "Who should we target next?",
        "Are you holding onto your items, or should we use them here?",
        "Whose fault is this current pinch, if you had to guess?",
        "Should we heal up properly before entering the next room?",
        "Whose clutch play was that just now?",
        "Are we playing it safe with this choice, or going with pure momentum?",
        "Is there a real risk of a wipe here, or can we handle it?",
        "If you trust your gut, left or right for the next path?",
        "Should we save our progress now or push ahead?",
        "Where do you think this enemy's weak point is?",
        "Who should we give this new piece of equipment to?",
        "Did you barely dodge that attack, or did you take it full-on?",
        "Who is going to take on the role of bait for the next plan?",
        "Is the word 'retreat' starting to cross your mind yet?",
        "Who is brave enough to try disarming this suspicious trap?",
        "Should we reapply buffs and heals right now?",
        "Do you think we can turn the tables all at once from here?",
        "Do you have a bad feeling about the next event?",
        "Do you feel like this choice is going to trap us in a loop?",
        "Who are we going to tease for that recent mistake?",
        "Are our remaining HPs in the safe zone, or danger zone?",
        "Should we finally unleash our big skills and ultimate moves?",
        "Is there anything left to explore before moving to the next area?",
        "Did anyone come up with a good breakthrough strategy for this?",
        "Wasn't that combo just satisfyingly smooth?",
        "Aren't there way too many enemies right now, or is it just me?",
        "What is your go-to healing method right now?",
        "Should we charge in all-or-nothing right here?",
        "What's your plan for the next turn?",
        "Are we going to seriously regret this choice later?",
        "Did you get a scare from friendly fire or getting caught in an AoE?",
        "Do you think the boss is past the halfway mark on HP yet?",
        "Did that damage hurt, or was it nothing?",
        "Can we power through this pinch with pure grit?",
        "In what order should we take our next actions?",
        "Are we about to run out of in-game funds soon?",
        "Is everyone going to agree on this choice right away?",
        "Should we take a moment to regroup and replan?",
        "Who should get to land the stylish final blow?"
    ]
};
